In [1]:
import numpy as np

In [3]:
a = np.arange(4,10)
a

array([4, 5, 6, 7, 8, 9])

In [8]:
a.dtype, a.itemsize, a.shape, a.ndim

(dtype('int32'), 4, (6,), 1)

In [13]:
c,d =  a.max(),  a.cumsum()
c,d

(9, array([ 4,  9, 15, 22, 30, 39], dtype=int32))

In [14]:
arr = np.zeros((2,2,2,2))
arr

array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]])

In [16]:
arr = np.ones((2,2,2,2), dtype=int)
arr

array([[[[1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1]]],


       [[[1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1]]]])

In [18]:
arr = np.arange(0, 2, 0.3, dtype=float)
arr

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [23]:
arr = np.linspace(2.,100,num=48,endpoint=True)
arr

array([  2.        ,   4.08510638,   6.17021277,   8.25531915,
        10.34042553,  12.42553191,  14.5106383 ,  16.59574468,
        18.68085106,  20.76595745,  22.85106383,  24.93617021,
        27.0212766 ,  29.10638298,  31.19148936,  33.27659574,
        35.36170213,  37.44680851,  39.53191489,  41.61702128,
        43.70212766,  45.78723404,  47.87234043,  49.95744681,
        52.04255319,  54.12765957,  56.21276596,  58.29787234,
        60.38297872,  62.46808511,  64.55319149,  66.63829787,
        68.72340426,  70.80851064,  72.89361702,  74.9787234 ,
        77.06382979,  79.14893617,  81.23404255,  83.31914894,
        85.40425532,  87.4893617 ,  89.57446809,  91.65957447,
        93.74468085,  95.82978723,  97.91489362, 100.        ])

In [24]:
a = np.arange(4,10).reshape(2,3)
a

array([[4, 5, 6],
       [7, 8, 9]])

In [25]:
import sys 

In [26]:
print(sys.maxsize)

9223372036854775807


In [28]:
B = np.array( [[2,0],
            [3,4]] )
A = np.array( [[5,6],
            [7,8]] )

In [29]:
A*B# elementwise product

array([[10,  0],
       [21, 32]])

In [30]:
A@B

array([[28, 24],
       [38, 32]])

In [31]:
A.dot(B)

array([[28, 24],
       [38, 32]])

In [32]:
A+B

array([[ 7,  6],
       [10, 12]])

In [37]:
A-B

array([[3, 6],
       [4, 4]])

In [36]:
B.reshape(1,4)

array([[2, 0, 3, 4]])

In [50]:
arr = np.linspace(2.,100,num=8,endpoint=True)
arr=arr.reshape(2,4)
arr

array([[  2.,  16.,  30.,  44.],
       [ 58.,  72.,  86., 100.]])

In [55]:
arr.resize(4,2)
arr

array([[  2.,  16.],
       [ 30.,  44.],
       [ 58.,  72.],
       [ 86., 100.]])

In [56]:
arr.ravel()

array([  2.,  16.,  30.,  44.,  58.,  72.,  86., 100.])

In [57]:
arr.T

array([[  2.,  30.,  58.,  86.],
       [ 16.,  44.,  72., 100.]])

In [59]:
A, B

(array([[5, 6],
        [7, 8]]), array([[2, 0],
        [3, 4]]))

In [61]:
np.vstack([A,B])

array([[5, 6],
       [7, 8],
       [2, 0],
       [3, 4]])

In [64]:
np.hstack([A,B])

array([[5, 6, 2, 0],
       [7, 8, 3, 4]])

In [69]:
arr

array([[  2.,  16.],
       [ 30.,  44.],
       [ 58.,  72.],
       [ 86., 100.]])

In [72]:
np.hsplit(arr,2)

[array([[ 2.],
        [30.],
        [58.],
        [86.]]), array([[ 16.],
        [ 44.],
        [ 72.],
        [100.]])]

In [73]:
#hstack, vstack, column_stack, concatenate, c_, r_

np.r_['0,2,0', [1,2,3], [4,5,6]]


array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [74]:
np.r_['0,2,1', [1,2,3], [4,5,6]]


array([[1, 2, 3],
       [4, 5, 6]])

In [85]:
np.r_['1,2,3', [1,2,3], [4,5,6]] # axes,dim,


ValueError: axes don't match array